### ISSUE TITLE
Production use of NVIDIA DRA resource driver

### ISSUE THREAD

**Issue by hase1128** [NVIDIA/k8s-dra-driver#131]
The current Readme of NVIDIA DRA resource driver states the following:

> This DRA resource driver is currently under active development and not yet designed for production use.

If you have a plan to improve it so that it can be used in production environments, please let me know the timing.
(For example, the same time as the K8s DRA itself becomes GA, etc.)

Also, if NVIDIA officially supports the NVIDIA DRA resource driver, will it be published in the catalog below?
https://catalog.ngc.nvidia.com/containers?filters=&orderBy=weightPopularDESC&query=&page=&pageSize=

**Comment by JasonHe-WQ** [comment]
> The current Readme of NVIDIA DRA resource driver states the following:
> 
> > This DRA resource driver is currently under active development and not yet designed for production use.
> 
> If you have a plan to improve it so that it can be used in production environments, please let me know the timing. (For example, the same time as the K8s DRA itself becomes GA, etc.)
> 
> Also, if NVIDIA officially supports the NVIDIA DRA resource driver, will it be published in the catalog below? https://catalog.ngc.nvidia.com/containers?filters=&orderBy=weightPopularDESC&query=&page=&pageSize=

As the sig-node documents mentioned, the DRA seems to still a long long way to actual production. GA will **not** be [soon](https://github.com/kubernetes/enhancements/blob/4243722b9f3cb87233719e50f75e59a990823d59/keps/sig-node/3063-dynamic-resource-allocation/README.md?plain=1#L931)

**Comment by klueska** [comment]
Closing as I belive the question has been answered. Please reopen if you disagree or would like to discuss further.
