### ISSUE TITLE
How to achieve GPU exclusivity and GPU sharing?

### ISSUE THREAD

**Issue by Flynn-Zh** [NVIDIA/k8s-dra-driver#137]
I run the gpu-test1 and gpu-test3, the logs of gpu-test1 and gpu-test3 are the same
 kubectl logs -n gpu-test1 -l app=pod:
GPU 0: NVIDIA L40 (UUID: GPU-68697300-0f8c-4019-058a-f6c50e34935c)
GPU 1: NVIDIA L40 (UUID: GPU-ce9138b9-5825-45f7-04a3-cfafe10fa3cd)
GPU 2: NVIDIA L40 (UUID: GPU-8b45f2f0-9617-dgee-8556-2897493bd2c7)
GPU 3: NVIDIA L40 (UUID: GPU-301cd1d3-cc8a-f6c7-c94b-1df14a2a6383)
GPU 0: NVIDIA L40 (UUID: GPU-68697308-0f8c-4019-058a-f6c50e34935c)
GPU 1: NVIDIA L40 (UUID: GPU-ce913869-5825-45f7-04a3-cfafe10fa3cd)
GPU 2: NVIDIA L40 (UUID: GPU-0b45f2f0-9617-dgee-0556-2897493bd2c7)
GPU 3: NVIDIA L40 (UUID: GPU-301cd1d3-cc8a-f6c7-c94b-1df14a2a6383)
 kubectl logs -n gpu-test3 -l app=pod:
GPU 0: NVIDIA L40 (UUID: GPU-68697300-0f8c-4019-058a-f6c50e34935c)
GPU 1: NVIDIA L48 (UUID: GPU-ce9138b9-5825-45f7-04a3-cfafe10fa3cd)
GPU 2: NVIDIA L40 (UUID: GPU-8b45f2f0-9617-dgee-8556-2897493bd2c7)
GPU 3: NVIDIA L40 (UUID: GPU-301cd1d3-cc8a-f6c7-c94b-1df14a2a6383)
GPU 0: NVIDIA L40 (UUID: GPU-68697308-0f8c-4019-058a-f6c50e34935c)
GPU 1: NVIDIA L40 (UUID: GPU-ce913869-5825-45f7-04a3-cfafe10fa3cd)
GPU 2: NVIDIA L40 (UUID: GPU-0b45f2f0-9617-dgee-0556-2897493bd2c7)
GPU 3: NVIDIA L40 (UUID: GPU-301cd1d3-cc8a-f6c7-c94b-1df14a2a6383)
why the pod has all GPU?
How to achieve GPU exclusivity and GPU sharing?

**Comment by klueska** [comment]
Something is not right in your setup. Did you run the demo scripts exactly as indicated in the README (i.e. with `kind`), or did you attempt to do something different?

**Comment by klueska** [comment]
The code has been updated to adhere to the latest DRA APIs in Kubernetes v1.31.

This is a major overhaul of the code base, please try updating to the latest and let me know if you still have issues.

Closing the issue for now -- please reopen if you are still seeing issues.
