### ISSUE TITLE
Is there any document about how to install dra in an existing k8s cluster?

### ISSUE THREAD

**Issue by sparkleMing** [NVIDIA/k8s-dra-driver#141]

**Comment by hasenbam** [comment]
I am wondering as well.
Is the driver in this repository actually working for compute or is this just a dummy implementation so far?

**Comment by klueska** [comment]
As of today, the driver on main only works on Kubernetes 1.26-1.29. it can be used to run GPU workloads, but it is not production ready by any means. In the next few weeks, I plan to update the code in this repod to work with the newest DRA APIs introduced in Kubernetes 1.31. An official release is planned to coincide with DRA itself going beta (which is currently planned for 1.32 in December 2024).

**Comment by klueska** [comment]
Closing for now, please reopen if you need more clarification or would like to discuss further.
