### ISSUE TITLE
 unknown field

### ISSUE THREAD

**Issue by 13567436138** [NVIDIA/k8s-dra-driver#144]
root@k8s-master01:~/k8s-dra-driver# kubectl logs nvidia-dra-k8s-dra-driver-kubelet-plugin-6dwrr -n nvidia-dra
Defaulted container "plugin" out of: plugin, init (init)
W0723 10:45:38.823998       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.cudaDriverVersion"
W0723 10:45:38.824041       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.driverVersion"
I0723 10:45:38.838612       1 device_state.go:146] using devRoot=/driver-root
W0723 10:45:38.841493       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.cudaDriverVersion"
W0723 10:45:38.841507       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.driverVersion"
W0723 10:45:38.845637       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.cudaDriverVersion"
W0723 10:45:38.845649       1 warnings.go:70] unknown field "spec.allocatableDevices[0].gpu.driverVersion"

**Comment by klueska** [comment]
This means you didn't rebuild / reinstall your CRDs after updating the code base from an earlier release.
