### ISSUE TITLE
dra static resourceClaim is ok，but dynamic is not ok？no error log

### ISSUE THREAD

**Issue by 13567436138** [NVIDIA/k8s-dra-driver#145]
https://github.com/kubernetes/kubernetes/issues/126320

**Comment by klueska** [comment]
What do you mean by "static" claim vs. "dynamic" claim?

**Comment by klueska** [comment]
Closing for now due to lack of response. Please reopen if you are still having issues with the latest code (which has changed significantly to support Kubernetes v1.31).
