### ISSUE TITLE
dra did not create ResourceSlice api，so I create one，but get none

### ISSUE THREAD

**Issue by 13567436138** [NVIDIA/k8s-dra-driver#146]
https://github.com/kubernetes/kubernetes/issues/126346

**Comment by klueska** [comment]
This code base has not been updated to adhere to the latest APIs introduced in Kubernetes 1.30 and 1.31 (where the `ResourceSlice` was introduced). We plan to update to this repo in the next few weeks, so stay tuned. The logic will be similar to what I added in https://github.com/kubernetes-sigs/dra-example-driver.

**Comment by klueska** [comment]
The code has been updated to adhere to the latest DRA APIs in Kubernetes v1.31, including the creation of ResourceSlices.
