### ISSUE TITLE
Does dra-driver need a resource controller ?

### ISSUE THREAD

**Issue by AllenXu93** [NVIDIA/k8s-dra-driver#165]
In DRA kubernetes , it always need 2 component which are device-plugin and controller;
But in GPU driver, there is only a device-plugin;
I found a commit that remove controller, is the controller move to other repo or some other reason ?
https://github.com/NVIDIA/k8s-dra-driver/commit/6e988d445f64ab0893210060c872c2ab011fce7d

**Comment by klueska** [comment]
In 1.31 DRA has moved away from what we have been calling "classic DRA" (which required a controller) to a new model called "structured parameters" (which no longer requires a controller). The repo has been updated to adhere to the new "structured parameters" way of doing things for 1.31.

There is still some limited support for "classic DRA" in 1.31, but it will be completely removed in 1.32, so it is not worth the effort to try to continue to maintain it.

**Comment by AllenXu93** [comment]
> In 1.31 DRA has moved away from what we have been calling "classic DRA" (which required a controller) to a new model called "structured parameters" (which no longer requires a controller). The repo has been updated to adhere to the new "structured parameters" way of doing things for 1.31.
> 
> There is still some limited support for "classic DRA" in 1.31, but it will be completely removed in 1.32, so it is not worth the effort to try to continue to maintain it.

Thanks for reply.If I want to use Nvidia DRA in early version like 1.28 / 1.29, is `classic-dra` branch can work for me ?

**Comment by klueska** [comment]
Yes, the `classic-dra` branch will continue to work for older versions of kubernetes, but we don't plan to make updates to it going forward.
