### ISSUE TITLE
Does the nvidia dra-driver support structed parameter DRA?

### ISSUE THREAD

**Issue by fj-zhang-lei** [NVIDIA/k8s-dra-driver#177]
I saw this commit in main branch.
I think in main branch nvidia dra-driver support structed parameter DRA and not support classic DRA, am I right?

```
commit 6c8d69f6c80a00b4e8a23a2d8ff2d0c2f4831d42
Author: Kevin Klues <kklues@nvidia.com>
Date:   Thu Sep 5 14:19:17 2024 +0000

    Remove support for classic DRA

    Signed-off-by: Kevin Klues <kklues@nvidia.com>
```

**Comment by klueska** [comment]
That is correct. The main branch only supports structured parameters now. The support for classic DRA (only on pre-1.31 clusters) still exists on the "classic-dra" branch of the repo.
