### ISSUE TITLE
Add status to resourceclaimtemplate

### ISSUE THREAD

**Issue by asm582** [NVIDIA/k8s-dra-driver#21]
Resource claim is created and consumed by the pod but it does not have the status or event:

```
Name:         gpu.example.com
Namespace:    gpu-test1
Labels:       <none>
Annotations:  <none>
API Version:  resource.k8s.io/v1alpha2
Kind:         ResourceClaimTemplate
Metadata:
  Creation Timestamp:  2023-11-16T21:20:04Z
  Resource Version:    29288
  UID:                 13584603-d6ae-4576-a799-919f10d6283e
Spec:
  Metadata:
    Creation Timestamp:  <nil>
  Spec:
    Allocation Mode:      WaitForFirstConsumer
    Resource Class Name:  gpu.example.com
Events:                   <none>
```

Such a notification would be helpful when user uses `Immediate` mode.

**Comment by klueska** [comment]
What event are you expecting to see here?

**Comment by asm582** [comment]
Hi @klueska , We would like to have a status of the claim like `claim-config-completed` with an event that describes a node name.

**Comment by klueska** [comment]
Yes, I notice there is no `Status` field in a `ResourceClaimTemplate`:
https://github.com/kubernetes/kubernetes/blob/c28c2009181fcc44c5f6b47e10e62dacf53e4da0/pkg/apis/resource/types.go#L397

You would need to open an issue against kubernetes itself, as `ResourceClaimTemplate` is an in-tree abstraction (not something specific to our driver).

**Comment by asm582** [comment]
Thanks, I created this issue, Hopefully its in the correct place: https://github.com/kubernetes/kubernetes/issues/121987
