### ISSUE TITLE
Unclear field definition gpuClaimName in MigDeviceClaimParameters

### ISSUE THREAD

**Issue by cyclinder** [NVIDIA/k8s-dra-driver#68]
Hi, I noticed that `GpuClaimParametersName` is the name of the `ResourceClaim` and not the `GpuClaimParameters`,right?

https://github.com/NVIDIA/k8s-dra-driver/blob/b6c7aae2b87d857668f417689462da752090406f/api/nvidia.com/resource/gpu/v1alpha1/migclaim.go#L29

Refer to https://docs.google.com/document/d/1BNWqgx_SmZDi-va_V31v3DnuVwYnF2EmN7D-O_fB6Oo:

>  This object also includes a forward reference to the (yet-to-be-created) resource claim of the MIG enabled GPU on which this MIG device should be created  (shared-gpu). Note this is the name of the resource claim itself, not the claim parameters object we called mig-enabled-gpu

If so, this may be ambiguous and we should update it to avoid ambiguity:

GpuClaimParametersName -> GpuResourceClaimName

**Comment by klueska** [comment]
This is now gone as the latest DRA APIs do not support ClaimParameters in the same way. The alternative / new way to do the same thing that this field was meant to accomplish can be seen in this (working) example: https://github.com/NVIDIA/k8s-dra-driver/blob/28a410ed4c9e5a9d324b9d81dad86f242b7806ef/demo/specs/quickstart/gpu-test4.yaml
