### ISSUE TITLE
镜像无法拉取

### ISSUE THREAD

**Issue by KeKouShi** [NVIDIA/k8s-dra-driver#91]
使用helm创建之后，pod状态是ErrImagePull，原因是
Failed to pull image "nvcr.io/nvidia/cloud-native/k8s-dra-driver:v0.1.0": rpc error: code = Unknown desc = failed to pull and unpack image "nvcr.io/nvidia/cloud-native/k8s-dra-driver:v0.1.0"
deployments/helm/k8s-dra-driver/values.yaml里imagePullSecrets是空的，使用docker pull nvcr.io/nvidia/cloud-native/k8s-dra-driver:v0.1.0提示401 Authorization Required
请问需要怎么解决

**Comment by s04** [comment]
你可以使用 Github 容器注册表中的镜像，因为目前 NVIDIA 容器注册表是私有的。

你可以在这里找到镜像：https://github.com/NVIDIA/k8s-dra-driver/pkgs/container/k8s-dra-driver

同时，你需要在 Helm Chart 的值中替换镜像标签，位于这里：https://github.com/NVIDIA/k8s-dra-driver/blob/main/deployments/helm/k8s-dra-driver/values.yaml

请注意，由于缺少对应的 v0.1.0 标签，这可能是一个不稳定的版本

**Comment by KeKouShi** [comment]
谢谢，现在可以拉取镜像了
